### ISSUE TITLE
App Store Connect asks  if my app use the IDFA 

### ISSUE THREAD

**Issue by qliqdev** [once10301/udid#2]
in udid/ios/Classes/YDDevice.m 
you imported 
`#import <AdSupport/ASIdentifierManager.h>`

is it necessary  to use your plugin? Cuz despite of that app store connect requires Advertising Identifier.

**Comment by ctkqiang** [comment]
> in udid/ios/Classes/YDDevice.m
> you imported
> `#import <AdSupport/ASIdentifierManager.h>`
> 
> is it necessary to use your plugin? Cuz despite of that app store connect requires Advertising Identifier.

Developer is not replying?
